import OffersList from "../components/offers/OffersList";

const mockOffers = [
  {
    segment: "Top Spenders",
    offerText: "Offer a 15% VIP Loyalty Discount on next purchase."
  },
  {
    segment: "At-Risk",
    offerText: "Send a 10% reactivation coupon valid for 7 days."
  },
  {
    segment: "New Customers",
    offerText: "Welcome gift: Free shipping on the next order."
  }
];

export default function OffersPage() {
  return (
    <div>
      <h1>Targeted Offers</h1>
      <p>
        These are sample AI-recommended offers for each customer segment. 
        Later this will be dynamically generated by the backend.
      </p>

      <OffersList offers={mockOffers} />
    </div>
  );
}